### ISSUE TITLE
Check al links on website, many might be broken

### ISSUE THREAD

**Issue by matiasandina** [open-neuroscience/open-neuroscience.github.io#12]
Is there a way to check that the links on the posts are not broken? [Example post](https://open-neuroscience.com/staging/en/post/schematics-posner-test/)

**Comment by matiasandina** [comment]
Related, should we have something that says "this project is no longer maintained/has moved to..." ?

**Comment by amchagas** [comment]
ok. 
so I had a browse though the pages and here is a sum up of broken links/images (there might be more, but I think it would be a pretty good advance if we dealt with these):

 
### Update (some have faulty html code, some miss image, some have layout issues, etc)

- ~~[ ] Super releaser page needs an image. It also has turned to a company, and I couldn't find the documentation on a quick look at their page~~ for the sake of finishing this clean up and getting a move to deploy the new website, I would simply remove this for now. 

- [x]  data repositories 
- [x]  autoreward 2 | Don't have the pictures for this one, we could borrow from [Open Behavior](https://edspace.american.edu/openbehavior/2017/05/26/autoreward2/) or from wherever they were stored previously **contact Jesus Ballesteros, who developed this. He contributed with Open Neuroscience some time ago**
- [x] big neuron
- [x] BPM biosignal (image) | Wasn't clear at all what was the image, put link to their youtube channel
- [x] brain browser (image)
- [x]  data acquisition and signal processing - Renamed this to brainflow, as it was the only project listed there
- [x]  fingertip laser (image)
- [x]  green brain (image)
- [x]  ipipet
- [x] lab management software (image)
- [x] neuromorpho (image)
- [x] neurobytes (embedded video) (project is now called neurotinker. I've updated it with a featured image instead of video - andre 05-05-2020)
- [x] nibabel | not sure what to do with all the `{.reference.external}`
- [x] nipy
- [x] nosepoke device

~~- [ ] open hand~~ this project is now continued as openbionics (which has a page on open neuroscience)

- [x] open microscopy environment
- [x] open flexure
- [x] open fuge (image)
- [x] pulse pal
- [x] psychophysics toolboxes
- [x] python, numpy, scipy
- [x] raspberry pi based
- [x] red pitaya
- [x] school of data
- [x] spike gadgets 
- [x] Skinner box with RPi + python | possible fix, can't say for sure until it renders


### Remove
- [ ] Open Prosthetics and Robots page is an umbrella page (just references other internal pages). But then we need to add openrobothardware.org and sofrobotstoolkit.con (as they are only referenced on this page)
- [x] Arduino posner test
- [x] schematics posner test
- [x] Neuroimage database is umbrella
- [x] microcontrollers is umbrella
- [x]  computer clusters is umbrella
- [x]  computers is umbrella
- [x]  data analysis page is umbrella
- [x]  database & sharing is umbrella
- [x] microscopes is umbrella
- [x]  human psychophysics using arduino 
- [x] opening MCD files with python
- [x]  python record script posner test

**Comment by matiasandina** [comment]
Cool, I will do the remove ones first.
I will try to do the others as I can. Sometimes it happened that I didn't know what the solution was, I might need help for those (e.g., locating the actual picture or video that was supposed to show). I guess #1 can help identify those.

**Comment by amchagas** [comment]
no worries, let me know the ones you need help with and I can try to work them out on my end!

**Comment by amchagas** [comment]
Just dropping a message here to ping you, since I've worked on some posts!

**Comment by amchagas** [comment]
ok, mostly done. the two projects that need new page, I'll add as new issues and we can contact the maintainers of the projects when our form system is up and running..
